#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# init-wordpress.sh — versión robusta
# Resuelve: getenv_docker() bug + permissions en wp-config.php
# ─────────────────────────────────────────────────────────────────
set -e

cd /var/www/html

# ─────────────────────────────────────────────────────────────────
# Paso 1: esperar a wp-config.php
# ─────────────────────────────────────────────────────────────────
echo "⏳ Esperando a que wp-config.php exista..."
for i in $(seq 1 60); do
  if [ -f wp-config.php ]; then
    echo "✅ wp-config.php existe."
    break
  fi
  sleep 2
done

if [ ! -f wp-config.php ]; then
  echo "❌ wp-config.php no apareció."
  exit 1
fi

# ─────────────────────────────────────────────────────────────────
# Paso 2: forzar permisos de escritura
# ─────────────────────────────────────────────────────────────────
echo "🔧 Ajustando permisos..."
chmod 666 wp-config.php

# ─────────────────────────────────────────────────────────────────
# Paso 3: escribir wp-config.php desde cero (evita getenv_docker bug)
# ─────────────────────────────────────────────────────────────────
echo "🔧 Escribiendo wp-config.php con DB hardcoded..."
cat > wp-config.php <<'WPCONFIG'
<?php
/**
 * WordPress configuration — auto-generated by AI Website Bridge init.
 */

// ** Database settings ** //
define( 'DB_NAME',     'wordpress' );
define( 'DB_USER',     'wordpress' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST',     'mysql' );
define( 'DB_CHARSET',  'utf8mb4' );
define( 'DB_COLLATE',  '' );

/**#@+
 * Authentication unique keys and salts.
 * Placeholders — WordPress will replace on first admin login if desired.
 */
define( 'AUTH_KEY',         'aiw-placeholder-auth-key-replace-in-production' );
define( 'SECURE_AUTH_KEY',  'aiw-placeholder-secure-auth-key' );
define( 'LOGGED_IN_KEY',    'aiw-placeholder-logged-in-key' );
define( 'NONCE_KEY',        'aiw-placeholder-nonce-key' );
define( 'AUTH_SALT',        'aiw-placeholder-auth-salt' );
define( 'SECURE_AUTH_SALT', 'aiw-placeholder-secure-auth-salt' );
define( 'LOGGED_IN_SALT',   'aiw-placeholder-logged-in-salt' );
define( 'NONCE_SALT',       'aiw-placeholder-nonce-salt' );
/**#@-*/

$table_prefix = 'wp_';

define( 'WP_DEBUG',         true );
define( 'WP_DEBUG_DISPLAY', false );
define( 'WP_DEBUG_LOG',     true );

define( 'DISALLOW_FILE_EDIT', true );
define( 'AUTOMATIC_UPDATER_DISABLED', true );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
WPCONFIG

# Re-ajustar permisos después de reescribir
chmod 666 wp-config.php
echo "✅ wp-config.php escrito con DB hardcoded."

# ─────────────────────────────────────────────────────────────────
# Paso 4: verificar DB
# ─────────────────────────────────────────────────────────────────
echo "🔌 Verificando conexión a MySQL..."
if wp db check --allow-root 2>&1 | head -3; then
  echo "✅ Conexión DB OK."
else
  echo "❌ No se pudo conectar a MySQL. Reintentando en 5s..."
  sleep 5
  wp db check --allow-root 2>&1 | head -3
fi

# ─────────────────────────────────────────────────────────────────
# Paso 5: instalar WP
# ─────────────────────────────────────────────────────────────────
if ! wp core is-installed --allow-root 2>/dev/null; then
  echo "📦 Instalando WordPress..."
  wp core install \
    --url="http://localhost:8000" \
    --title="AI Agent Demo Site" \
    --admin_user="admin" \
    --admin_password="admin" \
    --admin_email="admin@example.com" \
    --skip-email \
    --allow-root
  echo "✅ WordPress instalado."
else
  echo "✅ WordPress ya estaba instalado."
fi

# ─────────────────────────────────────────────────────────────────
# Paso 6: plugins
# ─────────────────────────────────────────────────────────────────
echo "📦 Activando AI Website Bridge plugin..."
wp plugin activate ai-website-bridge --allow-root 2>/dev/null || true

echo "📦 Instalando y activando Elementor..."
wp plugin install elementor --activate --allow-root 2>/dev/null || echo "⚠️  Elementor ya estaba instalado"

# ─────────────────────────────────────────────────────────────────
# Paso 7: páginas de ejemplo
# ─────────────────────────────────────────────────────────────────
echo "📄 Creando páginas de ejemplo..."
for TITLE in "Inicio" "Nosotros" "Servicios" "Contacto"; do
  if ! wp post list --post_type=page --title="$TITLE" --format=ids --allow-root 2>/dev/null | grep -q .; then
    wp post create --post_title="$TITLE" --post_status=publish --post_type=page --allow-root >/dev/null
  fi
done
if ! wp post list --post_type=page --title="Promociones" --format=ids --allow-root 2>/dev/null | grep -q .; then
  wp post create --post_title="Promociones" --post_status=draft --post_type=page --allow-root >/dev/null
fi

# Marcar como editables con Elementor
for PAGE_ID in $(wp post list --post_type=page --format=ids --allow-root 2>/dev/null); do
  wp post meta update "$PAGE_ID" _elementor_edit_mode "builder" --allow-root 2>/dev/null || true
  wp post meta update "$PAGE_ID" _elementor_template_type "wp-page" --allow-root 2>/dev/null || true
  wp post meta update "$PAGE_ID" _elementor_version "3.20.0" --allow-root 2>/dev/null || true
done
echo "✅ Páginas creadas."

# ─────────────────────────────────────────────────────────────────
# Paso 8: API Key
# ─────────────────────────────────────────────────────────────────
API_KEY="${DEFAULT_WP_API_KEY:-demo-key-change-in-production-please}"

echo "🔑 Creando API Key para el AI Agent..."
wp eval "
update_option('ai_agent_api_keys', [
  [
    'key_hash' => wp_hash_password('${API_KEY}'),
    'user_id'  => 1,
    'label'    => 'Default Agent Key',
    'created'  => current_time('mysql'),
    'last_used'=> null,
  ]
]);
" --allow-root

echo ""
echo "════════════════════════════════════════════════════════════"
echo "🎉 WordPress inicializado correctamente."
echo "════════════════════════════════════════════════════════════"
echo "  WordPress:    http://localhost:8000"
echo "  Admin:        http://localhost:8000/wp-admin (admin/admin)"
echo "  REST:         http://localhost:8000/wp-json/ai-agent/v1/"
echo "  API Key:      ${API_KEY}"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Probar:"
echo "  curl -H 'X-AI-Agent-Key: ${API_KEY}' http://localhost:8000/wp-json/ai-agent/v1/health"
